spring.application.name=rapidroute


spring.datasource.url=jdbc:postgresql://db.nlkflijetmzujcfzxrqr.supabase.co:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres
spring.datasource.password=Rohitrock4544@



spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
server.port=8080