spring.application.name=rapidroute

# Render Internal PostgreSQL Database
spring.datasource.url=jdbc:postgresql://dpg-d7h67dbeo5us739punjg-a/rapidroutedb
spring.datasource.username=rapidroutedb_user
spring.datasource.password=TZ6dgOu0r4sP6Z4qLE8OpWx2MramZR1n

# HikariCP settings
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080